### ISSUE TITLE
support for large-scaled hyperparameters or not?

### ISSUE THREAD

**Issue by lijiaqi** [awslabs/adatune#6]
Thanks for making this package public.

Does this package support for large-scaled hyperparameters? 

For examples, as we know, the hyperparameter optimization problems can be mathematically formulated as bilevel programming problems. If the variables in inner optimization(parameters) and in outer optimization(hyperparameters) are equal and both in the scale of neural networks weights, does this package still work?

**Comment by jmikko** [comment]
No, practically this would not work because of too high computational complexity.
